extraction:
  cpp:
    after_prepare: 
      - python report.py 23
  cobol:
    after_prepare: 
      - python report.py 23
  csharp:
    after_prepare: 
      - python report.py 23
  java:
    after_prepare: 
      - python report.py 23
  javascript:
    after_prepare: 
      - python report.py 23
  python:
    after_prepare: 
      - python report.py 23
